### PR TITLE
if field not optional validate on blur

### LINKED ISSUE #853: Display error message at point of error, not at Confirm & Submit
Please change Vireo 4 to behave like Vireo 3 in regard to error notices  (ie a required field was skipped, the wrong format was used, etc.)  Several testers noted that they would like this functionality returned to the way it was in Vireo 3 and not wait until the Confirm & Submit page to learn there are errors that need to be corrected.

### PR DESCRIPTION
**Pull request by wwelling**
Validation occurs on server side during the submission. If a field is modified it attempts to save onblur. Therefor, most cases the validation error would display. In the case of skipping a required was the only case not displaying a validation message when desired. Simple onblur will now attempt to save a required field whether it has been changed or not.

closes #853

### CODE REVIEW

File: src/main/webapp/app/directives/fieldProfileDirective.js [hunk 1]
```diff
@@ -38,8 +38,9 @@ vireo.directive("field", function ($controller, $filter, $q, $timeout, FieldValu
             $scope.save = function (fieldValue) {
                 // give typeahead select time to save the value
                 $timeout(function () {
+                    console.log($scope.profile);
```
Comment (kaladay) [inline src/main/webapp/app/directives/fieldProfileDirective.js]: Please remove console log.
