### PR TITLE
fixed umi release not showing in submission status sidebox and added …

### LINKED ISSUE #844: Display UMI Release in submission view status
If the ProQuest license has been accepted, UMI Release will be yes, otherwise no.

### PR DESCRIPTION
**Pull request by cstarcher**
…gloss

resolves #844

### CODE REVIEW

File: src/main/webapp/app/controllers/submission/adminSubmissionViewController.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-vireo.controller("AdminSubmissionViewController", function ($anchorScroll, $controller, $location, $q, $routeParams, $scope, DepositLocationRepo, EmailTemplateRepo, FieldPredicateRepo, FieldValue, FileUploadService, SidebarService, SubmissionRepo, SubmissionStatusRepo, UserRepo, UserService, UserSettings, SubmissionStatuses) {
+vireo.controller("AdminSubmissionViewController", function ($anchorScroll, $controller, $filter, $location, $q, $routeParams, $scope, DepositLocationRepo, EmailTemplateRepo, FieldPredicateRepo, FieldValue, FileUploadService, NamedSearchFilterGroup, SidebarService, SubmissionRepo, SubmissionStatusRepo, UserRepo, UserService, UserSettings, SubmissionStatuses) {
```
Comment (wwelling) [inline src/main/webapp/app/controllers/submission/adminSubmissionViewController.js]: looks like you dont need to inject $filter or NamedSearchFilterGroup

Comment (cstarcher) [reply src/main/webapp/app/controllers/submission/adminSubmissionViewController.js]: agreed, I forgot to remove them

File: src/main/webapp/app/controllers/submission/adminSubmissionViewController.js [hunk 2]
```diff
@@ -332,9 +332,13 @@ vireo.controller("AdminSubmissionViewController", function ($anchorScroll, $cont
             return $scope.submission.actionLogs[index].entry;
         };
 
-        // TODO: determine how this is set
         var isUmiRelease = function() {
-            return 'no';
+            var umiReleaseFilterFieldValue = $scope.submission.fieldValues.filter(function (fv) {
```
Comment (wwelling) [inline src/main/webapp/app/controllers/submission/adminSubmissionViewController.js]: sorry, one more change. umiRelease should by default be 'no' just in case the predicate umi_publication doesnt exist

File: src/main/webapp/app/controllers/submission/adminSubmissionViewController.js [hunk 3]
```diff
@@ -332,9 +332,14 @@ vireo.controller("AdminSubmissionViewController", function ($anchorScroll, $cont
             return $scope.submission.actionLogs[index].entry;
         };
 
-        // TODO: determine how this is set
         var isUmiRelease = function() {
-            return 'no';
+            var umiRelease = 'no';
+            var umiReleaseFilterFieldValue = $scope.submission.fieldValues.filter(function (fv) {
+                if(fv.fieldPredicate.value === "umi_publication") {
+                    umiRelease = fv.value === 'true' ? 'yes' : 'no';
```
Comment (wwelling) [inline src/main/webapp/app/controllers/submission/adminSubmissionViewController.js]: once again sorry, can you break out of the for loop when field value with predicate umi_publication is found

break;

File: src/main/webapp/app/controllers/submission/adminSubmissionViewController.js [hunk 4]
```diff
@@ -332,9 +332,15 @@ vireo.controller("AdminSubmissionViewController", function ($anchorScroll, $cont
...
+                    break;
```
Comment (wwelling) [inline src/main/webapp/app/controllers/submission/adminSubmissionViewController.js]: oh boy. cant break from filter. sorry, my bad. should consider using a for loop to avoid iterating over all field values. please remove break and we can merge
